In [19]:
import numpy as np
A = np.array([[25,0,1],[20,1,2],[40,1,6]])
b = np.array([[110],[110],[210]])

# To see rank, use: 
# np.linalg.matrix_rank(A)

# To invert a matrix, use:
# np.linalg.inv(A)

# To multiply matrices in Python 3, use:
# A@B

# x=solve(A,b)
x, residuals, rank, s = np.linalg.lstsq(A,b)
print(x)
print(residuals+rank)

[[ 4.25]
 [17.5 ]
 [ 3.75]]
[]


<ipython-input-19-021c92eacac1>:15: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  x, residuals, rank, s = np.linalg.lstsq(A,b)


In [25]:
import numpy as np
from scipy.linalg import solve

A = np.array([[20,12,8,1,2],[40,30,10,1,6], [30,15,15,0,3], [35,20,15,2,4]])
b = np.array([[97],[193],[132],[174]])

print(np.linalg.matrix_rank(A))

# x=solve(A,b)
# print(x)
# Note: you can use np.hstack() to concatinate vectors, for example np.hstack((A,b))
x, residuals, rank, s = np.linalg.lstsq(A,b)
print(x)
print(residuals)
# Note: you can select all the columns, except the first of a matrix A as:  A[:,1:]

4
[[2.66666667]
 [1.33333333]
 [1.33333333]
 [9.        ]
 [4.        ]]
[]


<ipython-input-25-bb542a699560>:12: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  x, residuals, rank, s = np.linalg.lstsq(A,b)


In [27]:
import numpy as np 
  
# input two matrices 
mat1 = ([0.5,0.5],[0.5,-0.5],[0.5,-0.5],[0.5,0.5]) 
mat2 = ([1,1,1],[1,-2,1]) 


# res = np.dot(mat1,mat2) 
# print(res)
# print(np.linalg.matrix_rank(res))

x, residuals, rank, s = np.linalg.lstsq(res,b)
print(x)
print(residuals)

[[ 94.83333333]
 [108.33333333]
 [ 94.83333333]]
[]


<ipython-input-27-3f8568d78e5a>:12: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  x, residuals, rank, s = np.linalg.lstsq(res,b)


In [22]:
import numpy as np
A = np.array([[1,0],[1,-1],[0,1]])
b = np.array([[-1],[2],[1]])

# To see rank, use: 
# np.linalg.matrix_rank(A)

# To invert a matrix, use:
# np.linalg.inv(A)

# To multiply matrices in Python 3, use:
# A@B

# x=solve(A,b)
x, residuals, rank, s = np.linalg.lstsq(A,b)
print(x)
print(residuals)
# print(residuals+rank)

[[ 0.33333333]
 [-0.33333333]]
[5.33333333]


<ipython-input-22-cc775bc5d10c>:15: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  x, residuals, rank, s = np.linalg.lstsq(A,b)
