In [1]:
# a)
import numpy as np
from scipy.io import loadmat
import matplotlib.pyplot as plt
in_data = loadmat('face_emotion_data.mat')
y = in_data['y']
X = in_data['X']

In [2]:
 w= np.linalg.inv(X.T@X)@X.T@y
print(w)

[[ 0.94366942]
 [ 0.21373778]
 [ 0.26641775]
 [-0.39221373]
 [-0.00538552]
 [-0.01764687]
 [-0.16632809]
 [-0.0822838 ]
 [-0.16644364]]


In [3]:
# b) If the new image has a input vector of x, the predicted label for
# this image is sign(x@w). If the result is +1 then the image is a happy face, otherwise
# an angry faces.

In [4]:
# c) the first feature vector is more important: since it is 0.94, which is the largest value among all vectors

In [5]:
# d)
# easy to find that vectors with greatest values should be used to build classifier
X3 = X[:,[0,2,3]]
w3 = np.linalg.inv(X3.T@X3)@X3.T@y
print(w3)

[[ 0.70546316]
 [ 0.8737872 ]
 [-0.78805643]]


In [6]:
# e)
error = len([1 for i in np.hstack((np.sign(X@w), y)) if i[0]!=i[1]])
print("error rate 9 features: ",error/len(np.sign(X@w))*100,"%")
error_vec_3 = len([1 for i in np.hstack((np.sign(X3@w3), y)) if i[0]!=i[1]])
print("error rate 3 features: ",error_vec_3/len(np.sign(X3@w3))*100,"%")

error rate 9 features:  2.34375 %
error rate 3 features:  6.25 %


In [10]:
# f)

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
# %%javascript
# IPython.OutputArea.auto_scroll_threshold = 9999

for i in range(8):
 hold = [j for j in range(i*16,i*16+16)]
 error = len([1 for i in np.hstack((np.sign(X[hold,:]@w), y[hold])) if i[0]!=i[1]])
 learn = [j for j in range(len(X)) if j not in hold]
 w = np.linalg.inv(X[learn,:].T@X[learn,:])@X[learn,:].T@y[learn] 
 error=error/len(y[hold])*100  
    
 print(i," Holdout set: ",hold)
 print(i," Training set: ",learn)
 print(i," iteration: error rate ",error,"%")
 print(i," iteration: weight: \n",w)
 print("---------------------------------------------------------------------------------------------")

0  Holdout set:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
0  Training set:  [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127]
0  iteration: error rate  0.0 %
0  iteration: weight: 
 [[ 0.91041778]
 [ 0.00918976]
 [ 0.40141401]
 [-0.32425274]
 [-0.05200825]
 [ 0.01241881]
 [-0.11750884]
 [-0.03420966]
 [-0.10223542]]
---------------------------------------------------------------------------------------------
1  Holdout set:  [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
1  Training set:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 